---
title: "Simulation wa-E"
author: "Jeremy J Lin"
date: "`r Sys.Date()`"
output: 
  pdf_document :
    keep_tex: true
    extra_dependencies: "subfig"
header-includes:
 - \usepackage{booktabs}
 - \usepackage{longtable}
 - \usepackage{array}
 - \usepackage{multirow}
 - \usepackage{wrapfig}
 - \usepackage{float}
 - \usepackage{subfig}
 - \floatplacement{figure}{H}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(nlme)
library(Matrix)
library(MASS)
library(rootSolve)
library(geepack)
library(lme4)
library(mvtnorm)
library(reshape2)
library(knitr)
library(ggplot2)
library(tidyr)
library(gridExtra)
library(tidyverse)
library(dplyr)
library(kableExtra)
library(corrplot)
library(robustHD)
library(pracma)
library(xtable)
library(latex2exp)
library(janitor)
library(ggpubr)
# parallel computing libraries
library(foreach)
#library(doMC)
# beep beep 
library(beepr)
library(doParallel)
library(doSNOW)
library(utils)
library(foreach)
library(doRNG)
library(geepack)
```

```{r echo=FALSE}
#rm(list = ls())

knitr::opts_chunk$set(echo = FALSE, message = FALSE, 
                      warning = FALSE, results = "hide", 
                      fig.pos = 'H', cache = FALSE, 
                      eval = FALSE)
# load functions
source("~/Research/LMM_Project/dgm simutlations/R_functions.R")
```

<!-- Functions -->
```{r}
# change font size, legend position
myggfont <- function(legend_pos = NULL,
                     legend_text_size = 18,
                     legend_title_size = 20,
                     axis_text_size = 16,
                     axis_title_size = 20,
                     plot_title_size = 20,
                     facet_text_size = 9) {
  ff <- theme(legend.text = element_text(size = legend_text_size),
              legend.title = element_text(size = legend_title_size),
              axis.text = element_text(size = axis_text_size),
              axis.title = element_text(size = axis_title_size, face="bold"),
              plot.title = element_text(size = plot_title_size),
              strip.text.x = element_text(size = facet_text_size),
              strip.text.y = element_text(size = facet_text_size))
  if (is.null(legend_pos)) {
    return(ff)
  } else if (legend_pos == "top-left") {
    return(ff + theme(legend.justification = c(0,1), legend.position = c(0,1)))
  } else if (legend_pos == "top-right") {
    return(ff + theme(legend.justification = c(1,1), legend.position = c(1,1)))
  } else if (legend_pos == "bottom-left") {
    return(ff + theme(legend.justification = c(0,0), legend.position = c(0,0)))
  } else if (legend_pos == "bottom-right") {
    return(ff + theme(legend.justification = c(1,0), legend.position = c(1,0)))
  } else {
    stop("legend_pos needs to be NULL, top-left, top-right, bottom-left, or bottom-right.")
  }
}

```

```{r}
result7.1 <- readRDS("result_7_1_df_collected_nsim1000.RDS")
result7.1$correct_tau <- "2. correct form"
result7.3 <- readRDS("result_7_3_df_collected_nsim1000.RDS")
result7.3$correct_tau <- "1. incorrect form and incorrect AA"
result7.2 <- readRDS("result_7_2_df_collected_nsim1000.RDS")
result7.2$correct_tau <- "3. incorrect form but correct AA"
result <- rbind(result7.1, result7.2, result7.3)


```


```{r}

```



```{r}
# visualize the effect of treatment effect to power 
result %>%  filter(gamma5 == 0 ) %>% 
  ggplot(aes(x = gamma3, y = power_adj, color = gamma4, group = gamma4)) +
  geom_line()+ 
  facet_grid(~correct_tau)+
    xlab(TeX(r'($\gamma_3)')) +
  ylab("power") +
    #ggtitle(TeX(r'($EO^w(t)$: weekend effect)')) +
    scale_color_continuous(name = TeX(r'($\gamma_4^*$)')) +
    coord_cartesian(ylim = c(0.7, 0.9), xlim = c(-0.2, 0.2)) +
    scale_y_continuous(breaks = seq(from = 0.1, to = 1, by = 0.1)) +
    scale_x_continuous(breaks = c(-0.2,0,0.2)) +
    # facet_grid(gt_t_theta ~ ASPNC_t, labeller = label_both) +
    theme_bw() + 
    myggfont() +
    theme(legend.text.align = 0, plot.title = element_text(hjust = 0.5))
ggsave(paste0("figure 7.1.1 - power.pdf"), width = 8, height = 8) 
```

```{r}
# visualize the effect of treatment effect to power 
result %>%  filter(gamma4 == 0 ) %>% 
  ggplot(aes(x = gamma5, y = power_adj, color = gamma3, group = gamma3)) +
  geom_line()+ 
  facet_grid(~correct_tau)+    
  xlab(TeX(r'($\gamma_5)')) +
  ylab("power") +
    #ggtitle(TeX(r'($EO^w(t)$: weekend effect)')) +
    scale_color_continuous(name = TeX(r'($\gamma_3^*$)')) +
    coord_cartesian(ylim = c(0.7, 0.9), xlim = c(-0.2, 0.2)) +
    scale_y_continuous(breaks = seq(from = 0.1, to = 1, by = 0.1)) +
    scale_x_continuous(breaks = c(-0.2,0,0.2)) +
    # facet_grid(gt_t_theta ~ ASPNC_t, labeller = label_both) +
    theme_bw() + 
    myggfont() +
    theme(legend.text.align = 0, plot.title = element_text(hjust = 0.5))
ggsave(paste0("figure 7.1.2 - power.pdf"), width = 8, height = 8) 
```
```{r}
result$gamma3_gamma4 <- paste0("gamma3 ", result$gamma3," gamma 4 ",result$gamma4)
result$gamma3_plus_gamma4 <- result$gamma3 + result$gamma4
result %>% 
  ggplot(aes(x = gamma5, y = power_adj, color = gamma3_gamma4)) +
  geom_line(alpha = 0.2)+ 
  facet_grid(~correct_tau)+
  xlab(TeX(r'($\gamma_5)')) +
  ylab("power") +
    #ggtitle(TeX(r'($EO^w(t)$: weekend effect)')) +
    #scale_color_continuous(name = TeX(r'($\gamma_3^*$)')) +
    coord_cartesian(ylim = c(0.7, 0.9), xlim = c(-0.2, 0.2)) +
    scale_y_continuous(breaks = seq(from = 0.1, to = 1, by = 0.1)) +
    scale_x_continuous(breaks = c(-0.2,0,0.2)) +
    # facet_grid(gt_t_theta ~ ASPNC_t, labeller = label_both) +
    theme_bw() + 
    myggfont() +
    theme(legend.position = "none")
ggsave(paste0("figure 7.1.3 - power.pdf"), width = 8, height = 8) 
```

```{r}
result$gamma3_gamma4 <- paste0("gamma3 ", result$gamma3," gamma 4 ",result$gamma4)
result$gamma3_plus_gamma4 <- result$gamma3 + result$gamma4
result %>% filter(gamma3_gamma4 %in% c("gamma3 -0.2 gamma 4 -0.2" , "gamma3 0.2 gamma 4 -0.2", "gamma3 0.2 gamma 4 0", "gamma3 0 gamma 4 0", 
                                       "gamma3 0.2 gamma 4 0.2")) %>% 
  ggplot(aes(x = gamma5, y = power_adj, color = gamma3_gamma4)) +
  geom_line()+ 
  #theme(legend.position = "none")+
  facet_grid(~correct_tau)
```

