---
title: "Simulation 2"
author: "Jeremy J Lin"
date: "`r Sys.Date()`"
output: 
  pdf_document :
    keep_tex: true
    extra_dependencies: "subfig"
header-includes:
 - \usepackage{booktabs}
 - \usepackage{longtable}
 - \usepackage{array}
 - \usepackage{multirow}
 - \usepackage{wrapfig}
 - \usepackage{float}
 - \usepackage{subfig}
 - \floatplacement{figure}{H}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(nlme)
library(Matrix)
library(MASS)
library(rootSolve)
library(geepack)
library(lme4)
library(mvtnorm)
library(reshape2)
library(knitr)
library(ggplot2)
library(tidyr)
library(gridExtra)
library(tidyverse)
library(dplyr)
library(kableExtra)
library(corrplot)
library(robustHD)
library(pracma)
library(xtable)
library(latex2exp)
library(janitor)
library(ggpubr)
# parallel computing libraries
library(foreach)
#library(doMC)
# beep beep 
library(beepr)
library(doParallel)
library(doSNOW)
library(utils)
library(foreach)
library(doRNG)
library(geepack)
```

```{r echo=FALSE}
#rm(list = ls())

knitr::opts_chunk$set(echo = FALSE, message = FALSE, 
                      warning = FALSE, results = "hide", 
                      fig.pos = 'H', cache = FALSE, 
                      eval = FALSE)
# load functions
source("~/Research/LMM_Project/dgm simutlations/R_functions.R")
```

<!-- Functions -->

# Simulation Settings 


```{r}
# change font size, legend position
myggfont <- function(legend_pos = NULL,
                     legend_text_size = 18,
                     legend_title_size = 20,
                     axis_text_size = 22,
                     axis_title_size = 26,
                     plot_title_size = 20,
                     facet_text_size = 16) {
  ff <- theme(legend.text = element_text(size = legend_text_size),
              legend.title = element_text(size = legend_title_size),
              axis.text = element_text(size = axis_text_size),
              axis.title = element_text(size = axis_title_size, face="bold"),
              plot.title = element_text(size = plot_title_size),
              strip.text.x = element_text(size = facet_text_size),
              strip.text.y = element_text(size = facet_text_size))
  if (is.null(legend_pos)) {
    return(ff)
  } else if (legend_pos == "top-left") {
    return(ff + theme(legend.justification = c(0,1), legend.position = c(0,1)))
  } else if (legend_pos == "top-right") {
    return(ff + theme(legend.justification = c(1,1), legend.position = c(1,1)))
  } else if (legend_pos == "bottom-left") {
    return(ff + theme(legend.justification = c(0,0), legend.position = c(0,0)))
  } else if (legend_pos == "bottom-right") {
    return(ff + theme(legend.justification = c(1,0), legend.position = c(1,0)))
  } else {
    stop("legend_pos needs to be NULL, top-left, top-right, bottom-left, or bottom-right.")
  }
}
```


```{r}
n_seed = 1

SD = data.frame()
for (isim in 1:n_seed) {
  fileName = paste("results_sim_1_setting_",isim,"_",1000,".RDS",sep = "")
  res <- readRDS(paste0(fileName))
  print(length(res))
  SD <- rbind(SD, res)
}

saveRDS(SD, "n_vs_tau.RDS")

unique(paste0(SD$ft_t_shape, SD$ft_t_theta, SD$ft_t_theta2))
```


```{r}
# 1. Make plots for n versus ATE------------------------------------------------
    n_ATE <- readRDS("n_vs_tau.RDS")         
    
   n_ATE$ft_t_shape_and_ft_t_theta <- paste0(n_ATE$ft_t_shape, n_ATE$ft_t_theta,n_ATE$ft_t_theta2)
  unique(n_ATE$ft_t_shape_and_ft_t_theta)
  # only use data from aspnc = 0.08 since the pattern looks similar 
   n_ATE <- n_ATE %>% filter(ASPNC_t == 0.08)
   # reorder levels 
    #n_ATE$ft_t_shape_and_ft_t_theta <- factor( n_ATE$ft_t_shape_and_ft_t_theta, levels = c("constant000.08","linear_theta0.3-0.40.08",   #"linear_theta0.300.08", "linear_theta0.30.40.08"))
   
   # ggplot 
    n_ATE %>% 
    filter(!(ft_t_theta2 %in% c(-0.2,0.2))) %>%
    # filter(tau_t_shape == "linear") %>% 
    ggplot(aes(x = tau_t_theta, y = n, linetype = tau_t_shape, color = ft_t_shape_and_ft_t_theta)) +
    geom_line() +
    scale_color_discrete(name = "Pattern of MEE(t)",
                             labels = c(TeX(r'(constant)'),
                                        TeX(r'(linear, $\theta_{f2} = -0.4$)'),
                                        TeX(r'(linear, $\theta_{f2} = 0$)'),
                                        TeX(r'(linear, $\theta_{f2} = 0.4$)'))) +
    scale_linetype_discrete(name = TeX(r'(Pattern of $\tau(t)$)'),
                         labels = c("linear", "periodic")) +
    xlab(TeX(r'($\theta_\tau$)')) +
    ylab("n (sample size)") +
    theme_bw() + 
    myggfont() +
    theme(legend.text.align = 0, plot.title = element_text(hjust = 0.5))
    ggsave("size Drinkless 3 - n vs theta_tau.jpg", height = 4, width = 7)
    ggsave("size Drinkless 3 - n vs theta_tau.pdf", height = 4, width = 7)
```

