---
title: "Simulation 1_2"
author: "Jeremy J Lin"
date: "`r Sys.Date()`"
output: 
  pdf_document :
    keep_tex: true
    extra_dependencies: "subfig"
header-includes:
 - \usepackage{booktabs}
 - \usepackage{longtable}
 - \usepackage{array}
 - \usepackage{multirow}
 - \usepackage{wrapfig}
 - \usepackage{float}
 - \usepackage{subfig}
 - \floatplacement{figure}{H}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(nlme)
library(Matrix)
library(MASS)
library(rootSolve)
library(geepack)
library(lme4)
library(mvtnorm)
library(reshape2)
library(knitr)
library(ggplot2)
library(tidyr)
library(gridExtra)
library(tidyverse)
library(dplyr)
library(kableExtra)
library(corrplot)
library(robustHD)
library(pracma)
library(xtable)
library(latex2exp)
library(janitor)
library(ggpubr)
# parallel computing libraries
library(foreach)
#library(doMC)
# beep beep 
library(beepr)
library(doParallel)
library(doSNOW)
library(utils)
library(foreach)
library(doRNG)
library(geepack)
```

```{r echo=FALSE}
#rm(list = ls())

knitr::opts_chunk$set(echo = FALSE, message = FALSE, 
                      warning = FALSE, results = "hide", 
                      fig.pos = 'H', cache = FALSE, 
                      eval = TRUE)
```

<!-- Functions -->
```{r eval=FALSE}
# read simulation design 
n_seed = 2 
nsim = 1000

result_list = list()
isim =1 

for (isim in 1:n_seed) {
  fileName = paste("results_consistency_sim_setting_",isim,"_",nsim,".RDS",sep = "")
  res <- readRDS(paste0(fileName))
  print(length(res))
  result_list <- c(result_list, res)
}
length(result_list)


saveRDS(result_list, "result_list.RDS")


```

```{r}
result_list <- readRDS("result_list.RDS")
nsim = 1000
na_vec <- rep(NA, length(result_list))

coef_est <- data.frame(
  sample_size = na_vec,
  total_T = na_vec,
  bias_beta_1 = na_vec,
  bias_beta_2 = na_vec,
  th_se_beta_1 = na_vec,
  th_se_beta_2 = na_vec,
  beta_1_se = na_vec,
  beta_2_se = na_vec,
  beta_1_cp = na_vec,
  beta_2_cp = na_vec,
  beta_1_rmse = na_vec,
  beta_2_rmse = na_vec,
  th_se_beta_1_adj = na_vec,
  th_se_beta_2_adj = na_vec,
  beta_1_cp_adj_z = na_vec,
  beta_2_cp_adj_z = na_vec,
  beta_1_cp_adj_t = na_vec,
  beta_2_cp_adj_t = na_vec,
  beta_1_ci_lb_unadj = na_vec,
  beta_2_ci_lb_unadj = na_vec,
  beta_1_ci_ub_unadj = na_vec,
  beta_2_ci_ub_unadj = na_vec,
  beta_1_ci_lb_adj_z = na_vec,
  beta_2_ci_lb_adj_z = na_vec,
  beta_1_ci_ub_adj_z = na_vec,
  beta_2_ci_ub_adj_z = na_vec,
  beta_1_ci_lb_adj_t = na_vec,
  beta_2_ci_lb_adj_t = na_vec,
  beta_1_ci_ub_adj_t = na_vec,
  beta_2_ci_ub_adj_t = na_vec,
  converge_flag = na_vec,
  na_flag = na_vec, 
  sim = na_vec, 
  true_beta_1 = na_vec,
  true_beta_2 = na_vec
)
j = 1
betas <- c()

for(j in 1:length(result_list)) {
  n <- coef_est$sample_size[j]<- result_list[[j]]$sample_size
  t <- coef_est$total_T[j] <- result_list[[j]]$total_T
  # Calculate power
  data <- result_list[[j]]
  
  # Store the coefficient from lme for all simulation
  # row = coef, col = simulation
  param <- rowMeans(sapply(result_list[[j]]$result, function(l) l$beta_true), na.rm = TRUE)
  coef_method <- sapply(result_list[[j]]$result, function(l) l$beta_hat)
  th_se <- sapply(result_list[[j]]$result, function(l) l$beta_se)
  th_se_adj <- sapply(result_list[[j]]$result, function(l) l$beta_se_adjusted)
  ci_unadj_lb <- sapply(result_list[[j]]$result, function(l) l$ci_unadj[,1])
  ci_unadj_ub <- sapply(result_list[[j]]$result, function(l) l$ci_unadj[,2])
  ci_adj_lb_z <- sapply(result_list[[j]]$result, function(l) l$ci_adj_z[,1])
  ci_adj_ub_z <- sapply(result_list[[j]]$result, function(l) l$ci_adj_z[,2])
  ci_adj_lb_t <- sapply(result_list[[j]]$result, function(l) l$ci_adj_t[,1])
  ci_adj_ub_t <- sapply(result_list[[j]]$result, function(l) l$ci_adj_t[,2])
  conv_flag <- ifelse(colMeans(abs(coef_method)) < 5, 1, 0 )
  na_flag <- is.na(colMeans(coef_method))
  
  
  # Average of all betas (simulation  - true coef),
  coef_est[j, 3:4] <- rowMeans(coef_method, na.rm = TRUE) - param
  coef_est[j, 5:6] <- rowMeans(th_se, na.rm = TRUE)
  coef_est[j, 7:8] <- apply(coef_method, 1, function(x) sd(x, na.rm = TRUE))
  coef_est[j, 13:14] <- rowMeans(th_se_adj, na.rm = TRUE)
  coef_est[j,"converge_flag"] <- mean(conv_flag,na.rm = TRUE)
  coef_est[j, "na_flag"] <- sum(as.integer(na_flag))
  coef_est[j, "sim"] <- dim(coef_method)[2]/nsim 
  # flag result when coefficient is greater than 1
  
  # see if it's inside the confidence interval
  # see the binary yes or no cp
  # unadj cp
  coef_est[j, 9:10] <-
    sapply(1:2, function(i)
      mean(
        (param[i] >= ci_unadj_lb[i,] ) &
          (param[i] <= ci_unadj_ub[i,]), 
        na.rm = TRUE
      ))
  
  # coef_est[j, 59:62] <-
  #   sapply(1:4, function(i)
  #     mean(
  #       (param[i] >= coef_method[i,] - 1.96 * th_se[i,]) &
  #         (param[i] <= coef_method[i,] + 1.96 * th_se[i,]), 
  #        na.rm = TRUE
  #     ))
  
  # adj cp with z 
  coef_est[j, 15:16] <-
    sapply(1:2, function(i)
      mean(
        (param[i] >= ci_adj_lb_z[i,]) &
          (param[i] <= ci_adj_ub_z[i,]), 
         na.rm = TRUE
      ))
  
  # adj cp with t
  coef_est[j, 17:18] <-
    sapply(1:2, function(i)
      mean(
        (param[i] >= ci_adj_lb_t[i,]) &
          (param[i] <= ci_adj_ub_t[i,]), 
         na.rm = TRUE
      ))
  
  # mse = bias^2 + variance unadj
  coef_est[j, 11:12] <- sqrt((coef_est[j,3:4]) ^ 2 + (coef_est[j, 7:8]) ^ 2)
  
  # ci undajust lowerbound and upperbound
  coef_est[j, 19:20] <- rowMeans(ci_unadj_lb, na.rm = TRUE)
  coef_est[j, 21:22] <- rowMeans(ci_unadj_ub, na.rm = TRUE)
  
  # ci z-adjusted lowerbound and upperbound
  coef_est[j, 23:24] <- rowMeans(ci_adj_lb_z, na.rm = TRUE)
  coef_est[j, 25:26] <- rowMeans(ci_adj_ub_z, na.rm = TRUE)
  
  # ci t-adjusted lowerbound and upperbound
  coef_est[j, 27:28] <- rowMeans(ci_adj_lb_t, na.rm = TRUE)
  coef_est[j, 29:30] <- rowMeans(ci_adj_ub_t, na.rm = TRUE)
  
  # true paramete 
  coef_est[j ,34:35] <- data$true_beta
  
  # # ci unaddjusted manually calculated lowerbound and upperbound
  # coef_est[j, 63:66] <- rowMeans(coef_method - 1.96 * th_se, na.rm = TRUE)
  # coef_est[j, 67:70] <- rowMeans(coef_method + 1.96 * th_se, na.rm = TRUE)
  
}

saveRDS(coef_est, "coef_est.RDS")
```



```{r}
coef_est <- readRDS("coef_est.RDS")
coef_est %>% dplyr::select(sample_size, total_T,ends_with("_adj"), ends_with("_se"))
```


```{r}
beta_1_ci <- coef_est %>% dplyr::select(sample_size, beta_1_ci_lb_unadj, beta_1_ci_ub_unadj,beta_1_ci_lb_adj_z, beta_1_ci_ub_adj_z, beta_1_ci_lb_adj_t, beta_1_ci_ub_adj_t )

beta_2_ci <- coef_est %>% dplyr::select(sample_size, beta_2_ci_lb_unadj, beta_2_ci_ub_unadj,beta_2_ci_lb_adj_z, beta_2_ci_ub_adj_z, beta_2_ci_lb_adj_t, beta_2_ci_ub_adj_t )

```


```{r}
intercept_1 <- tibble(
  total_T = coef_est$total_T,
  Bias = coef_est$bias_beta_1,
  RMSE = coef_est$beta_1_rmse,
  CP = coef_est$beta_1_cp,
  CP_adj_z = coef_est$beta_1_cp_adj_z, 
  CP_adj_t = coef_est$beta_1_cp_adj_t
)



intercept_2 <- tibble(
  total_T = coef_est$total_T,
  Bias = coef_est$bias_beta_2,
  RMSE = coef_est$beta_2_rmse,
  CP = coef_est$beta_2_cp,
  CP_adj_z = coef_est$beta_2_cp_adj_z, 
  CP_adj_t = coef_est$beta_2_cp_adj_t,
)


```

```{r}
trt_1_tibble <- bind_cols(intercept_1) %>%
  mutate(Treatment = 1, sample_size = coef_est$sample_size) %>%
  dplyr::select(Treatment, sample_size, everything())
trt_2_tibble <- bind_cols(intercept_2, slope_2) %>%
  mutate(Treatment = 2, sample_size = coef_est$sample_size) %>%
  dplyr::select(Treatment, sample_size, everything())

estimator <- bind_rows(trt_1_tibble, trt_2_tibble)

result <- estimator %>%
  group_by(Treatment) %>%
  ungroup %>%
  mutate(Treatment = replace(Treatment, duplicated(Treatment), ''))

result
```

```{r results='asis', eval= TRUE}
print(
kable(
  result,
  format = "latex",
  booktabs = TRUE,
  caption = "Performance of MEE",
  col.names = c("Trt", "Sample size", rep(c("Total T","Bias", "RMSE", "CP", "CP(z-adj)","CP(t-adj)" ),2)),
  escape = FALSE,
  digits = 3
) %>%
  kable_styling(latex_options = c("HOLD_position", "scale_down"),
                full_width = T) %>%
  add_header_above(c(
    " " = 2,
    "Intercept" = 5,
    "Slope" = 5
  )) %>%
  row_spec(9, extra_latex_after = "\\cline{1-12}") %>%
  save_kable("result_table.tex", float = FALSE)

)
```




```{r}
# change font size, legend position
myggfont <- function(legend_pos = NULL,
                     legend_text_size = 22,
                     legend_title_size = 22,
                     axis_text_size = 22,
                     axis_title_size = 24,
                     plot_title_size = 22,
                     facet_text_size = 18) {
  ff <- theme(legend.text = element_text(size = legend_text_size),
              legend.title = element_text(size = legend_title_size),
              axis.text = element_text(size = axis_text_size),
              axis.title = element_text(size = axis_title_size, face="bold"),
              plot.title = element_text(size = plot_title_size),
              strip.text.x = element_text(size = facet_text_size),
              strip.text.y = element_text(size = facet_text_size))
  if (is.null(legend_pos)) {
    return(ff)
  } else if (legend_pos == "top-left") {
    return(ff + theme(legend.justification = c(0,1), legend.position = c(0,1)))
  } else if (legend_pos == "top-right") {
    return(ff + theme(legend.justification = c(1,1), legend.position = c(1,1)))
  } else if (legend_pos == "bottom-left") {
    return(ff + theme(legend.justification = c(0,0), legend.position = c(0,0)))
  } else if (legend_pos == "bottom-right") {
    return(ff + theme(legend.justification = c(1,0), legend.position = c(1,0)))
  } else {
    stop("legend_pos needs to be NULL, top-left, top-right, bottom-left, or bottom-right.")
  }
}
```


```{r}
beta_1_table <- coef_est %>% filter(total_T == 30) %>% dplyr::select(sample_size, ends_with("beta_1"), starts_with("beta_1"))
beta_2_table <- coef_est %>% filter(total_T == 30) %>% dplyr::select(sample_size, ends_with("beta_2"), starts_with("beta_2"))

```


```{r}
bias_dta <- tibble(n = coef_est$sample_size,
                   beta_1 = coef_est$bias_beta_1, 
                   beta_2 = coef_est$bias_beta_2)
bias_dta_long <- bias_dta %>% pivot_longer(!n, names_to = "coef", values_to = "bias") %>% mutate(trt = rep(c(1,2), length(bias_dta$n)))
```


```{r}
rmse_dta <- tibble(n = coef_est$sample_size,
                   beta_1 = coef_est$beta_1_rmse, 
                   beta_2 = coef_est$beta_2_rmse)
rmse_dta_long <- rmse_dta %>% pivot_longer(!n, names_to = "coef", values_to = "rmse") %>% mutate(trt = rep(c(1,2), length(bias_dta$n)))
```

```{r}
cp_dta <- tibble(n = coef_est$sample_size,
                   beta_1 = coef_est$beta_1_cp_adj_t, 
                   beta_2 = coef_est$beta_2_cp_adj_t)
cp_dta_long <- cp_dta %>% pivot_longer(!n, names_to = "coef", values_to = "cp") %>% mutate(trt = rep(c(1,2), length(bias_dta$n)))
```

```{r}
# create plot 
    p1 <- bias_dta_long %>% 
    ggplot(aes(x = n, y = bias, linetype = factor(trt))) +
    geom_line(size = 2) +
    geom_hline(yintercept = 0, linetype = 2) +
    # scale_color_discrete(name = TeX(r'(Coefficient)'),
    #                         labels = c(TeX(r'($beta_1$)'),
    #                                    TeX(r'($beta_2$)'),
    #                                    TeX(r'($beta_3$)'),
    #                                   TeX(r'($beta_4$)'))) +
    # scale_linetype_discrete(name = TeX(r'(trt)'),
    #                      labels = c(TeX(r'($A_t = 1$)'),
    #                                 TeX(r'($A_t = 2$)'))) +
    # scale_color_discrete(name = TeX(r'($ATE^* = ATE^w$, $ASPN^* = ASPN^w$)'),
    #                      labels = c(TeX(r'($ATE = 1.2$, $ASPN = 0.2$)'),
    #                                 TeX(r'($ATE = 1.2$, $ASPN = 0.3$)'),
    #                                 TeX(r'($ATE = 1.2$, $ASPN = 0.4$)'),
    #                                 TeX(r'($ATE = 1.3$, $ASPN = 0.2$)'),
    #                                 TeX(r'($ATE = 1.3$, $ASPN = 0.3$)'),
    #                                 TeX(r'($ATE = 1.3$, $ASPN = 0.4$)'))) +
    xlab(TeX(r'($n$)')) +
    ylab("bias") +
    #ggtitle(TeX(r'(bias versus $n$)')) +
    coord_cartesian(ylim = c(-0.03, 0.03)) +
    scale_y_continuous(breaks = seq(from = -0.3, to = 0.3, by = 0.01)) +
    scale_x_continuous(breaks = seq(from = 20, to = 100, by = 20)) +
    theme_bw() + 
    myggfont() + 
    theme(legend.position="none")+
    theme(legend.text.align = 0, plot.title = element_text(hjust = 0.5))
  
p1

ggsave(paste0("bias_plot_const.pdf"), width = 5.5, height = 5.5)
```
```{r}
# create plot 
    p2 <- rmse_dta_long %>% 
    ggplot(aes(x = n, y = rmse, linetype = factor(trt))) +
    geom_line(size = 2) +
    geom_hline(yintercept = 0, linetype = 2) +
    # scale_color_discrete(name = TeX(r'(Coefficient)'),
    #                         labels = c(TeX(r'($beta_1$)'),
    #                                    TeX(r'($beta_2$)'),
    #                                    TeX(r'($beta_3$)'),
    #                                   TeX(r'($beta_4$)'))) +
    scale_linetype_discrete(name = TeX(r'(trt)'),
                         labels = c(TeX(r'($A_t = 1$)'),
                                    TeX(r'($A_t = 2$)'))) +
    # scale_color_discrete(name = TeX(r'($ATE^* = ATE^w$, $ASPN^* = ASPN^w$)'),
    #                      labels = c(TeX(r'($ATE = 1.2$, $ASPN = 0.2$)'),
    #                                 TeX(r'($ATE = 1.2$, $ASPN = 0.3$)'),
    #                                 TeX(r'($ATE = 1.2$, $ASPN = 0.4$)'),
    #                                 TeX(r'($ATE = 1.3$, $ASPN = 0.2$)'),
    #                                 TeX(r'($ATE = 1.3$, $ASPN = 0.3$)'),
    #                                 TeX(r'($ATE = 1.3$, $ASPN = 0.4$)'))) +
    xlab(TeX(r'($n$)')) +
    ylab("RMSE") +
    #ggtitle(TeX(r'(RMSE versus $n$)')) +
    coord_cartesian(ylim = c(0.05, 0.3)) +
    scale_y_continuous(breaks = seq(from = 0, to = 1, by = 0.05)) +
    scale_x_continuous(breaks = seq(from = 20, to = 100, by = 20)) +
    theme_bw() + 
    myggfont() + 
    theme(legend.position="none")+
    theme(legend.text.align = 0, plot.title = element_text(hjust = 0.5))
p2

ggsave(paste0("rmse_plot_const.pdf"), width = 5.5, height = 5.5)
```

```{r}
# create plot 
    p3 <- cp_dta_long %>% 
    ggplot(aes(x = n, y = cp, linetype = factor(trt))) +
    geom_line(size = 2) +
    geom_hline(yintercept = 0.95, linetype = 2) +
    # scale_color_discrete(name = TeX(r'(Coefficient)'),
    #                         labels = c(TeX(r'($beta_1$)'),
    #                                    TeX(r'($beta_2$)'),
    #                                    TeX(r'($beta_3$)'),
    #                                   TeX(r'($beta_4$)'))) +
    scale_linetype_discrete(name = TeX(r'(trt)'),
                         labels = c(TeX(r'($A_t = 1$)'),
                                    TeX(r'($A_t = 2$)'))) +
    # scale_color_discrete(name = TeX(r'($ATE^* = ATE^w$, $ASPN^* = ASPN^w$)'),
    #                      labels = c(TeX(r'($ATE = 1.2$, $ASPN = 0.2$)'),
    #                                 TeX(r'($ATE = 1.2$, $ASPN = 0.3$)'),
    #                                 TeX(r'($ATE = 1.2$, $ASPN = 0.4$)'),
    #                                 TeX(r'($ATE = 1.3$, $ASPN = 0.2$)'),
    #                                 TeX(r'($ATE = 1.3$, $ASPN = 0.3$)'),
    #                                 TeX(r'($ATE = 1.3$, $ASPN = 0.4$)'))) +
    xlab(TeX(r'($n$)')) +
    ylab("Coverage Probability") +
    #ggtitle(TeX(r'(Coverage Probability versus $n$)')) +
    #coord_cartesian(ylim = c(0.9, 1.0)) +
    scale_y_continuous(breaks = seq(from = 0.1, to = 1, by = 0.01)) +
    scale_x_continuous(breaks = seq(from = 20, to = 100, by = 20)) +
    theme_bw() + 
    myggfont() + 
    theme(legend.text.align = 0, plot.title = element_text(hjust = 0.5))
p3

ggsave(paste0("cp_plot_const.pdf"), width = 6.5, height = 5.5)
```