---
title: "Simulation 3_1"
author: "Jeremy J Lin"
date: "`r Sys.Date()`"
output: 
  pdf_document :
    keep_tex: true
    extra_dependencies: "subfig"
header-includes:
 - \usepackage{booktabs}
 - \usepackage{longtable}
 - \usepackage{array}
 - \usepackage{multirow}
 - \usepackage{wrapfig}
 - \usepackage{float}
 - \usepackage{subfig}
 - \floatplacement{figure}{H}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(nlme)
library(Matrix)
library(MASS)
library(rootSolve)
library(geepack)
library(lme4)
library(mvtnorm)
library(reshape2)
library(knitr)
library(ggplot2)
library(tidyr)
library(gridExtra)
library(tidyverse)
library(dplyr)
library(kableExtra)
library(corrplot)
library(robustHD)
library(pracma)
library(xtable)
library(latex2exp)
library(janitor)
library(ggpubr)
# parallel computing libraries
library(foreach)
#library(doMC)
# beep beep 
library(beepr)
library(doParallel)
library(doSNOW)
library(utils)
library(foreach)
library(doRNG)
library(geepack)
```

```{r echo=FALSE}
#rm(list = ls())

knitr::opts_chunk$set(echo = FALSE, message = FALSE, 
                      warning = FALSE, results = "hide", 
                      fig.pos = 'H', cache = FALSE, 
                      eval = FALSE)
# load functions
source("~/Research/LMM_Project/dgm simutlations/R_functions.R")
```

<!-- Functions -->

# Simulation Settings 

```{r}
# change font size, legend position
myggfont <- function(legend_pos = NULL,
                     legend_text_size = 18,
                     legend_title_size = 20,
                     axis_text_size = 12,
                     axis_title_size = 20,
                     plot_title_size = 20,
                     facet_text_size = 16) {
  ff <- theme(legend.text = element_text(size = legend_text_size),
              legend.title = element_text(size = legend_title_size),
              axis.text = element_text(size = axis_text_size),
              axis.title = element_text(size = axis_title_size, face="bold"),
              plot.title = element_text(size = plot_title_size),
              strip.text.x = element_text(size = facet_text_size),
              strip.text.y = element_text(size = facet_text_size))
  if (is.null(legend_pos)) {
    return(ff)
  } else if (legend_pos == "top-left") {
    return(ff + theme(legend.justification = c(0,1), legend.position = c(0,1)))
  } else if (legend_pos == "top-right") {
    return(ff + theme(legend.justification = c(1,1), legend.position = c(1,1)))
  } else if (legend_pos == "bottom-left") {
    return(ff + theme(legend.justification = c(0,0), legend.position = c(0,0)))
  } else if (legend_pos == "bottom-right") {
    return(ff + theme(legend.justification = c(1,0), legend.position = c(1,0)))
  } else {
    stop("legend_pos needs to be NULL, top-left, top-right, bottom-left, or bottom-right.")
  }
}
```


```{r}
source("~/Documents/Research/causal-excursion-multi-treatment-binary-outcome/simulations/power_simulation /4. WA-c violated/sim_5_2a/utillity.R")
# read simulation design 
SD <- readRDS("~/Documents/Research/causal-excursion-multi-treatment-binary-outcome/simulations/power_simulation /4. WA-c violated/sim_5_2a/factorial_design.RDS")
n_seed = 36
nsim = 1000
truth_hypothesis = "H1"
dim(SD)

result_list = list()
for (isim in 1:n_seed) {
  fileName = paste("results_sim_5_2_setting_",isim,"_",nsim,".RDS",sep = "")
  res <- readRDS(paste0(fileName))
  print(length(res))
  result_list <- c(result_list, res)
}
length(result_list)

setting = length(result_list)
result_df_collected <- data.frame()
result_list_collected <- list()

start_time <- Sys.time()

for (isetting in 1:setting) {
  
  current_time <- Sys.time()
  print(Sys.time())
  print(paste0(round(difftime(current_time, start_time, units = "hours"), 2),
               " hours has lapsed."))
  cat("i =", isetting, "/", nrow(SD), "\n")
  
  #print(SD[i, ])
  
  i <- result_list[[isetting]]$setting
  result <- result_list[[isetting]]$result
  
  ## gamma, b, m
  gamma <- SD$gamma[i]
  b <- SD$b[i]
  m <- SD$m[i]
  
  ## n, p_w, q_w
  n <- SD$n[i]
  p_w <- SD$p_w[i]
  q_w <- SD$q_w[i]
  p_star <- SD$p_star[i] # This is the degree of freedom of T test
  p <- 2 *p_w # this is the dimension of beta
  q <- q_w
  
  ##### simulation begins #####
  test_stat_unadj <- sapply(result, function(l) l$test_stat_unadj)
  test_stat_adj <- sapply(result, function(l) l$test_stat_adj)
  
  # fit <- sapply(result, function(l) l$fit$beta_hat)
  # fit_mean <- colMeans(fit)
  
  cri_val <- (p_star * (n - q - 1)) / (n - p_star - q) *
    qf(1 - gamma, p_star, n - p_star - q)
  
  print(cri_val)
  

  if (truth_hypothesis == "H1") {
    power_unadj <- sum(test_stat_unadj > cri_val) / nsim
    power_adj <- sum(test_stat_adj > cri_val) / nsim
    power_vec <- c(power_unadj, power_adj)
    names(power_vec) <- c("power_unadj", "power_adj")
    print(power_vec)
  } else if (truth_hypothesis == "H0") {
    typeierror_unadj <- sum(test_stat_unadj > cri_val) / nsim
    typeierror_adj <- sum(test_stat_adj > cri_val) / nsim
    typeierror_vec <- c(typeierror_unadj,typeierror_adj )
    names(typeierror_vec) <- c("typeierror_unadj","typeierror_adj" )
    print(typeierror_vec)
  }

  result_df <- cbind(SD[i, ],
                     data.frame(power_unadj = power_unadj,
                                power_adj = power_adj))             
  
  result_df_collected <- rbind(result_df_collected, result_df)
  result_list_collected <- c(result_list_collected, list(list(
    result_df = result_df,
    test_stat_unadj = test_stat_unadj, 
    test_stat_adj = test_stat_adj
  )))
}
  saveRDS(result_df_collected, file = paste0("result_df_collected_nsim", nsim, ".RDS"))
  saveRDS(result_list_collected, file = paste0("result_list_collected_nsim", nsim, ".RDS"))
  write.csv(result_df_collected, file = paste0("result_df_collected_nsim", nsim, ".csv"))

```

```{r}
# 3. Make plots and tables ------------------------------------------------
    nsim <- 1000
    
    result <- readRDS(paste0("result_df_collected_nsim", nsim, ".RDS"))
    
    result$ASPNC_t_and_gt_shape_and_gt_t_theta <-
      paste0(result$ASPNC_t, result$gt_t_shape, result$gt_t_theta)
    result$gt_shape_and_gt_t_theta <-
      paste0(result$gt_t_shape, result$gt_t_theta)
    
    # added delta_ATE
    result$ratio_ATE <- round(result$ATE2_t / result$ATE1_t, 2) 
    
    result$ATE_t_and_ASPNC_t <- paste0(result$ratio_ATE, " ", result$ft_t_theta, " ",result$ft_t_shape)
    
    result$gt_shape_and_gt_t_theta[result$gt_shape_and_gt_t_theta == "linear_theta0"] <-
      "constant"
    #result$gt_shape_and_gt_t_theta[result$gt_shape_and_gt_t_theta == "constant0"] <-
      #"constant"
    
```

```{r}
result$ft_shape_and_ft_w_theta <- paste0(result$ft_w_shape, result$ft_w_theta)
result <- result %>% filter(! ft_shape_and_ft_w_theta %in% c("linear_theta0", "quadratic_theta0"))

result$tau_w_shape_and_tau_w_theta <- paste0(result$tau_w_shape, result$tau_w_theta)

result <- result %>% filter(! tau_w_shape_and_tau_w_theta %in% c("linear0", "sine0"))

result <- result %>% filter(tau_w_shape != "constant")

result$tau_w_shape_name <- result$tau_w_shape
result$tau_w_shape_name[result$tau_w_shape_name == "sine"] <- "periodic"
result$tau_w_shape_name <- factor(result$tau_w_shape_name)

levels(result$tau_w_shape_name) <- c("periodic"=TeX(r'($\tau^w(t)$: periodic)'),
                                     "linear"=TeX(r'($\tau^w(t)$: linear)'))

result %>%
    ggplot(aes(x = tau_w_theta, y = power_adj, linetype = factor(gt_shape_and_gt_t_theta),
               color = factor(ATE_t_and_ASPNC_t))) +
    geom_line() +
    # facet_grid(~ tau_t_shape_and_tau_t_theta, labeller = tau_t_shape_and_tau_t_theta_labeller) +
    facet_grid(~ tau_w_shape_name, labeller = label_parsed) +
    geom_hline(yintercept = 0.8, linetype = 2) +
    scale_linetype_discrete(name = TeX(r'(Pattern of $SPNC^*(t) = SPNC^w(t)$)'),
                            labels = c(TeX(r'(quadratic, $\theta_g^* = \theta_g^w = -0.3$)'),
                                       TeX(r'(quadratic, $\theta_g^* = \theta_g^w = 0$)'),
                                       TeX(r'(quadratic, $\theta_g^* = \theta_g^w = 0.3$)'))) +
    scale_color_discrete(name = TeX(r'(Pattern of $MEE^*(t) = MEE^w(t)$)'),
                         labels = c(TeX(r'($rATE = 1.23$ linear, $\theta_f^* = \theta_f^w = -0.3$)'),
                                    TeX(r'($rATE = 1.23$ linear, $\theta_f^* = \theta_f^w = 0.3$)'),
                                    TeX(r'($rATE = 1.33$ linear, $\theta_f^* = \theta_f^w = -0.3$)'),
                                    TeX(r'($rATE = 1.33$ linear, $\theta_f^* = \theta_f^w = 0.3$)')
                                    )) +
    xlab(TeX(r'($\theta_\tau^w$)')) +
    ylab("power") +
    coord_cartesian(ylim = c(0.7, 0.85), xlim = c(-0.2, 0.2)) +
    scale_x_continuous(breaks = c(-0.4, -0.2, 0, 0.2, 0.4)) +
    ggtitle(TeX(r'($\tau^*(t)$: constant)')) +
    theme_bw() + 
    myggfont() +
    theme(legend.text.align = 0, plot.title = element_text(hjust = 0.5))
ggsave(paste0("figure 5_2 - power.pdf"), width = 10, height = 6)
ggsave(paste0("figure 5_2 - power.jpg"), width = 10, height = 6)
unique(result$tau_t_shape_and_tau_t_theta)
```
```{r}
result %>% filter(ASPNC_t_and_gt_shape_and_gt_t_theta == "0.2quadratic_theta-0.3", ft_w_theta == -0.3, ATE1_w ==1.2, tau_w_shape== "linear") #dplyr::select(tau_w_shape,tau_w_theta, n)
```

