---
title: "Simulation"
author: "Jeremy J Lin"
date: "`r Sys.Date()`"
output: 
  pdf_document :
    keep_tex: true
    extra_dependencies: "subfig"
header-includes:
 - \usepackage{booktabs}
 - \usepackage{longtable}
 - \usepackage{array}
 - \usepackage{multirow}
 - \usepackage{wrapfig}
 - \usepackage{float}
 - \usepackage{subfig}
 - \floatplacement{figure}{H}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(nlme)
library(Matrix)
library(MASS)
library(rootSolve)
library(geepack)
library(lme4)
library(mvtnorm)
library(reshape2)
library(knitr)
library(ggplot2)
library(tidyr)
library(gridExtra)
library(tidyverse)
library(dplyr)
library(kableExtra)
library(corrplot)
library(robustHD)
library(pracma)
library(xtable)
library(latex2exp)
library(janitor)
library(ggpubr)
# parallel computing libraries
library(foreach)
#library(doMC)
# beep beep 
library(beepr)
library(doParallel)
library(doSNOW)
library(utils)
library(foreach)
library(doRNG)
library(geepack)
library(here)
```

```{r echo=FALSE}
#rm(list = ls())

knitr::opts_chunk$set(echo = FALSE, message = FALSE, 
                      warning = FALSE, results = "hide", 
                      fig.pos = 'H', cache = FALSE, 
                      eval = TRUE)
```

## Simulation Setting 

Data Generative Model

\begin{align*}
E(Y_t|H_t, A_t) &= \{0.2 \times 1_{(Z_t = 0)} + 0.5 \times 1_{(Z_t = 1)} + 0.4 \times 1_{(Z_t = 2)}\} e^{((0.1 \times 1_{(A_t = 1)} + 0.25 \times 1_{(A_t = 1)} ) \times 0.3 Z_t)}\\
Z_t &= (0, 1, 2) \text{ with equal probability.}\\
Y_t &\sim Bern(E(Y_t | H_t, A_t))
\end{align*}




<!-- Functions -->
```{r eval=FALSE}
# only run this chunk to read results from HPC
n_seed = 5
nsim = 1000

result_list = list()
isim =1 

for (isim in 1:n_seed) {
  fileName = paste("results_consistency_sim_setting_",isim,"_",nsim,".RDS",sep = "")
  res <- readRDS(paste0(fileName))
  print(length(res))
  result_list <- c(result_list, res)
}
length(result_list)


saveRDS(result_list, "result_list.RDS")


```

```{r, eval=FALSE}
#only run this chunk if we have new simulation from HPC
result_list <- readRDS("result_list_.RDS")
nsim = 1000
na_vec <- rep(NA, length(result_list))

# caclulated true value of CEE see goodnotes
true_beta1 <- log((0.2 * exp(0.1)+ 0.5 * exp(0.1 + 0.3) + 0.4 * exp(0.1 + 2* 0.3)) / (0.2 + 0.5 + 0.4))
true_beta2 <- log((0.2 * exp(0.25)+ 0.5 * exp(0.25 + 0.2) + 0.4 * exp(0.25 + 2* 0.2)) / (0.2 + 0.5 + 0.4))
param <- c(true_beta1, true_beta2)

coef_est <- data.frame(
  sample_size = na_vec,
  total_T = na_vec,
  bias_beta_1_emee = na_vec,
  bias_beta_2_emee = na_vec,
  bias_beta_1_GEE1 = na_vec, 
  bias_beta_2_GEE1 = na_vec,
  bias_beta_1_GEE2 = na_vec, 
  bias_beta_2_GEE2 = na_vec,
  thSE_beta_1_emee = na_vec,
  thSE_beta_2_emee = na_vec,
  thSE_beta_1_GEE1= na_vec,
  thSE_beta_2_GEE1 = na_vec,
  thSE_beta_1_GEE2= na_vec,
  thSE_beta_2_GEE2 = na_vec,
  SE_beta_1_emee = na_vec,
  SE_beta_2_emee = na_vec,
  SE_beta_1_GEE1 = na_vec,
  SE_beta_2_GEE1 = na_vec,
  SE_beta_1_GEE2 = na_vec,
  SE_beta_2_GEE2 = na_vec,
  RMSE_beta_1_emee = na_vec,
  RMSE_beta_2_emee = na_vec,
  RMSE_beta_1_GEE1 = na_vec,
  RMSE_beta_2_GEE1 = na_vec,
  RMSE_beta_1_GEE2 = na_vec,
  RMSE_beta_2_GEE2 = na_vec,
  # th_se_beta_1_adj_emee = na_vec,
  # th_se_beta_2_adj_emee = na_vec,
  cp_beta_1_emee = na_vec,
  cp_beta_2_emee = na_vec,
  cp_beta_1_GEE1 = na_vec,
  cp_beta_2_GEE1 = na_vec,
  cp_beta_1_GEE2 = na_vec,
  cp_beta_2_GEE2 = na_vec,
  beta_1_ci_lb_adj_t_emee = na_vec,
  beta_2_ci_lb_adj_t_emee = na_vec,
  beta_1_ci_lb_GEE1 = na_vec,
  beta_2_ci_lb_GEE1 = na_vec,
  beta_1_ci_ub_GEE1 = na_vec,
  beta_2_ci_ub_GEE1 = na_vec,
  beta_1_ci_lb_GEE2 = na_vec,
  beta_2_ci_lb_GEE2 = na_vec,
  beta_1_ci_ub_GEE2 = na_vec,
  beta_2_ci_ub_GEE2 = na_vec
)


for(j in 1:length(result_list)) {
  n <- coef_est$sample_size[j]<- result_list[[j]]$sample_size
  t <- coef_est$total_T[j] <- result_list[[j]]$total_T
  # Calculate power
  data <- result_list[[j]]
  
  # Store the coefficient from lme for all simulation
  # row = coef, col = simulation
  coef_method <- sapply(result_list[[j]]$result, function(l) l$beta_hat_emee)
  th_se <- sapply(result_list[[j]]$result, function(l) l$beta_se_emee)
  th_se_adj <- sapply(result_list[[j]]$result, function(l) l$beta_se_adjusted_emee)
  ci_adj_lb_t <- sapply(result_list[[j]]$result, function(l) l$ci_adj_t[,1])
  ci_adj_ub_t <- sapply(result_list[[j]]$result, function(l) l$ci_adj_t[,2])

  
  
  # Average of all betas (simulation  - true coef),
  coef_est[j, c("bias_beta_1_emee", "bias_beta_2_emee")] <- rowMeans(coef_method, na.rm = TRUE) - param
  coef_est[j, c("thSE_beta_1_emee", "thSE_beta_2_emee")] <- rowMeans(th_se_adj, na.rm = TRUE)
  coef_est[j, c("SE_beta_1_emee", "SE_beta_2_emee")] <- apply(coef_method, 1, function(x) sd(x, na.rm = TRUE))
  #coef_est[j, c("th_se_beta_1_adj_emee", "th_se_beta_2_adj_emee")] <- rowMeans(th_se_adj, na.rm = TRUE)

  
  # see if it's inside the confidence interval
  # adj cp with t
  coef_est[j, c("cp_beta_1_emee", "cp_beta_2_emee")] <-
    sapply(1:2, function(i)
      mean(
        (param[i] >= ci_adj_lb_t[i,]) &
          (param[i] <= ci_adj_ub_t[i,]), 
         na.rm = TRUE
      ))
  
  # mse = bias^2 + variance unadj
  coef_est[j, c("RMSE_beta_1_emee", "RMSE_beta_2_emee")] <- sqrt((coef_est[j, c("bias_beta_1_emee", "bias_beta_2_emee")]) ^ 2 + (coef_est[j, c("SE_beta_1_emee", "SE_beta_2_emee")] ) ^ 2)

  # ci t-adjusted lowerbound and upperbound
  coef_est[j, c("beta_1_ci_lb_adj_t_emee", "beta_2_ci_lb_adj_t_emee")] <- rowMeans(ci_adj_lb_t, na.rm = TRUE)
  coef_est[j, c("beta_1_ci_ub_adj_t_emee", "beta_2_ci_ub_adj_t_emee")] <- rowMeans(ci_adj_ub_t, na.rm = TRUE)

  
  # store coef from GEE1 
  coef_method_GEE1 <- sapply(result_list[[j]]$result, function(l) l$beta_hat_GEE1)
  th_se_GEE1 <- sapply(result_list[[j]]$result, function(l) l$beta_se_GEE1)
  ci_lb_GEE1 <- sapply(result_list[[j]]$result, function(l) l$ci_GEE1[,1])
  ci_ub_GEE1 <- sapply(result_list[[j]]$result, function(l) l$ci_GEE1[,2])
  
  coef_est[j, c("bias_beta_1_GEE1", "bias_beta_2_GEE1")] <- rowMeans(coef_method_GEE1, na.rm = TRUE) - param
  coef_est[j, c("thSE_beta_1_GEE1", "thSE_beta_2_GEE1")] <- rowMeans(th_se_GEE1, na.rm = TRUE)
  coef_est[j, c("SE_beta_1_GEE1", "SE_beta_2_GEE1")] <- apply(coef_method_GEE1, 1, function(x) sd(x, na.rm = TRUE))

  # see if it's inside the confidence interval
  # adj cp with t
  coef_est[j, c("cp_beta_1_GEE1", "cp_beta_2_GEE1")] <-
    sapply(1:2, function(i)
      mean(
        (param[i] >= ci_lb_GEE1[i,]) &
          (param[i] <= ci_ub_GEE1[i,]), 
         na.rm = TRUE
      ))
  
  # mse = bias^2 + variance unadj
  coef_est[j, c("RMSE_beta_1_GEE1", "RMSE_beta_2_GEE1")] <- sqrt((coef_est[j, c("bias_beta_1_GEE1", "bias_beta_2_GEE1")]) ^ 2 + (coef_est[j, c("SE_beta_1_GEE1", "SE_beta_2_GEE1")] ) ^ 2)

  # ci t-adjusted lowerbound and upperbound
  coef_est[j, c("beta_1_ci_lb_GEE1", "beta_2_ci_lb_GEE1")] <- rowMeans(ci_lb_GEE1, na.rm = TRUE)
  coef_est[j, c("beta_1_ci_ub_GEE1", "beta_2_ci_ub_GEE1")] <- rowMeans(ci_ub_GEE1, na.rm = TRUE)
  
  
  # store coef from GEE2 
  coef_method_GEE2 <- sapply(result_list[[j]]$result, function(l) l$beta_hat_GEE2)
  th_se_GEE2 <- sapply(result_list[[j]]$result, function(l) l$beta_se_GEE2)
  ci_lb_GEE2 <- sapply(result_list[[j]]$result, function(l) l$ci_GEE2[,1])
  ci_ub_GEE2 <- sapply(result_list[[j]]$result, function(l) l$ci_GEE2[,2])
  
  coef_est[j, c("bias_beta_1_GEE2", "bias_beta_2_GEE2")] <- rowMeans(coef_method_GEE2, na.rm = TRUE) - param
  coef_est[j, c("thSE_beta_1_GEE2", "thSE_beta_2_GEE2")] <- rowMeans(th_se_GEE2, na.rm = TRUE)
  coef_est[j, c("SE_beta_1_GEE2", "SE_beta_2_GEE2")] <- apply(coef_method_GEE2, 1, function(x) sd(x, na.rm = TRUE))

  # see if it's inside the confidence interval
  # adj cp with t
  coef_est[j, c("cp_beta_1_GEE2", "cp_beta_2_GEE2")] <-
    sapply(1:2, function(i)
      mean(
        (param[i] >= ci_lb_GEE2[i,]) &
          (param[i] <= ci_ub_GEE2[i,]), 
         na.rm = TRUE
      ))
  
  # mse = bias^2 + variance unadj
  coef_est[j, c("RMSE_beta_1_GEE2", "RMSE_beta_2_GEE2")] <- sqrt((coef_est[j, c("bias_beta_1_GEE2", "bias_beta_2_GEE2")]) ^ 2 + (coef_est[j, c("SE_beta_1_GEE2", "SE_beta_2_GEE2")] ) ^ 2)

  # ci t-adjusted lowerbound and upperbound
  coef_est[j, c("beta_1_ci_lb_GEE2", "beta_2_ci_lb_GEE2")] <- rowMeans(ci_lb_GEE2, na.rm = TRUE)
  coef_est[j, c("beta_1_ci_ub_GEE2", "beta_2_ci_ub_GEE2")] <- rowMeans(ci_ub_GEE2, na.rm = TRUE)
}

saveRDS(coef_est, "consistency_sim_non_const_pt.RDS")
```



```{r}
coef_est <- readRDS(here("dataset","consistency_sim_non_const_pt.RDS"))%>% dplyr::select(sample_size, starts_with("bias"), starts_with("SE"), starts_with("cp"), starts_with("RMSE"))
df_long <- coef_est %>%
  pivot_longer(
    cols = -c(sample_size),
    names_to  = c("metric", "param", "method"),
    names_pattern = "(bias|SE|cp|RMSE)_(beta_?[12])_(emee|GEE1|GEE2)",
    values_to = "value"
  ) %>%
  mutate(method = toupper(method)) %>%
  pivot_wider(
    names_from  = metric,
    values_from = value
  )
```

## Treatment 1 effect 

```{r, results='asis'}
result <- df_long %>% filter(param == "beta_1") %>% dplyr::select(-param) %>% 
  mutate(method = factor(method, levels = c("EMEE", "GEE1", "GEE2"))) %>%
  arrange(method, sample_size)

print(
kable(
  result,
  format = "latex",
  booktabs = TRUE,
  caption = "Performance of MEE",
  col.names = c("Sample size", "Method", "Bias", "SE", "CP", "RMSE"),
  escape = FALSE,
  digits = 5
) %>%
  kable_styling(latex_options = c("HOLD_position", "scale_down"),
                full_width = T) 
  #row_spec(9, extra_latex_after = "\\cline{1-12}") %>%
  #save_kable("result_table.pdf", float = FALSE)
)
```

## Treatment 2 effect 

```{r, results='asis'}
result <- df_long %>% filter(param == "beta_2") %>% dplyr::select(-param) %>% 
  mutate(method = factor(method, levels = c("EMEE", "GEE1", "GEE2"))) %>%
  arrange(method, sample_size)

print(
kable(
  result,
  format = "latex",
  booktabs = TRUE,
  caption = "Performance of MEE",
  col.names = c("Sample size", "Method", "Bias", "SE", "CP", "RMSE"),
  escape = FALSE,
  digits = 5
) %>%
  kable_styling(latex_options = c("HOLD_position", "scale_down"),
                full_width = T) 
  #row_spec(9, extra_latex_after = "\\cline{1-12}") %>%
  #save_kable("result_table.pdf", float = FALSE)
)
```
