---
title: "Simulation 2"
author: "Jeremy J Lin"
date: "`r Sys.Date()`"
output: 
  pdf_document :
    keep_tex: true
    extra_dependencies: "subfig"
header-includes:
 - \usepackage{booktabs}
 - \usepackage{longtable}
 - \usepackage{array}
 - \usepackage{multirow}
 - \usepackage{wrapfig}
 - \usepackage{float}
 - \usepackage{subfig}
 - \floatplacement{figure}{H}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(nlme)
library(Matrix)
library(MASS)
library(rootSolve)
library(geepack)
library(lme4)
library(mvtnorm)
library(reshape2)
library(knitr)
library(ggplot2)
library(tidyr)
library(gridExtra)
library(tidyverse)
library(dplyr)
library(kableExtra)
library(corrplot)
library(robustHD)
library(pracma)
library(xtable)
library(latex2exp)
library(janitor)
library(ggpubr)
# parallel computing libraries
library(foreach)
#library(doMC)
# beep beep 
library(beepr)
library(doParallel)
library(doSNOW)
library(utils)
library(foreach)
library(doRNG)
library(geepack)
```

```{r echo=FALSE}
#rm(list = ls())

knitr::opts_chunk$set(echo = FALSE, message = FALSE, 
                      warning = FALSE, results = "hide", 
                      fig.pos = 'H', cache = FALSE, 
                      eval = FALSE)
# load functions
source("~/Research/LMM_Project/dgm simutlations/R_functions.R")
```

<!-- Functions -->

# Simulation Settings 


```{r}
# change font size, legend position
myggfont <- function(legend_pos = NULL,
                     legend_text_size = 18,
                     legend_title_size = 20,
                     axis_text_size = 22,
                     axis_title_size = 26,
                     plot_title_size = 20,
                     facet_text_size = 16) {
  ff <- theme(legend.text = element_text(size = legend_text_size),
              legend.title = element_text(size = legend_title_size),
              axis.text = element_text(size = axis_text_size),
              axis.title = element_text(size = axis_title_size, face="bold"),
              plot.title = element_text(size = plot_title_size),
              strip.text.x = element_text(size = facet_text_size),
              strip.text.y = element_text(size = facet_text_size))
  if (is.null(legend_pos)) {
    return(ff)
  } else if (legend_pos == "top-left") {
    return(ff + theme(legend.justification = c(0,1), legend.position = c(0,1)))
  } else if (legend_pos == "top-right") {
    return(ff + theme(legend.justification = c(1,1), legend.position = c(1,1)))
  } else if (legend_pos == "bottom-left") {
    return(ff + theme(legend.justification = c(0,0), legend.position = c(0,0)))
  } else if (legend_pos == "bottom-right") {
    return(ff + theme(legend.justification = c(1,0), legend.position = c(1,0)))
  } else {
    stop("legend_pos needs to be NULL, top-left, top-right, bottom-left, or bottom-right.")
  }
}
```


```{r}
n_seed = 15

SD = data.frame()
for (isim in 1:n_seed) {
  fileName = paste("results_sim_6_setting_",isim,"_",1000,".RDS",sep = "")
  res <- readRDS(paste0(fileName))
  print(length(res))
  SD <- rbind(SD, res)
}

saveRDS(SD, "n_vs_ft_1.RDS")

unique(paste0(SD$ft_t_shape, SD$ft_t_theta, SD$ft_t_theta2))
```


```{r}
# 1. Make plots for n versus ATE------------------------------------------------
    n_ATE <- readRDS("n_vs_ft_1.RDS")
    
    n_constant_MEE_SPNC <- n_ATE$n[n_ATE$ft_t_shape == "constant" & n_ATE$gt_t_shape == "constant"][1]
    n_constant_MEE <- n_ATE$n[n_ATE$ft_t_shape == "constant" & n_ATE$gt_t_theta == 0.2]
    n_ATE %>% filter(ft_t_shape == "constant") %>% dplyr::select(gt_t_shape, gt_t_theta, n)
    
    # ggplot 
    n_ATE %>% 
    filter(ft_t_shape != "constant") %>% 
    filter(gt_t_theta == 0.2) %>% 
    ggplot(aes(x = ft_t_theta, y = n)) +
    geom_line() +
    geom_hline(aes(yintercept = n_constant_MEE_SPNC, linetype = "constant SPNC(t)")) + 
    geom_hline(aes(yintercept = n_constant_MEE, linetype = "linear SPNC(t)")) + 
    xlab(TeX(r'($\theta_{f1}$)')) +
    ylab("n (sample size)") +
    coord_cartesian(ylim = c(350, 1100)) +
    # annotate("text", x = 0, y = n_constant_MEE_SPNC + 20, 
    #          label = paste0("constant MEE(t) & SPNC(t): n = ", n_constant_MEE_SPNC), size = 5) +
    # annotate("text", x = 0, y = n_constant_MEE - 2, 
    #          label = paste0("constant MEE(t) : n = ", n_constant_MEE), size = 5) +
    theme_bw() + 
    myggfont() +
    scale_linetype_manual(
    name = "constant MEE(t)",
    values = c(
      "constant SPNC(t)" = "dashed",
      "linear SPNC(t)" = "dotted"
    ))+
    theme(legend.text.align = 0, plot.title = element_text(hjust = 0.5))
    ggsave("size Drinkless n vs ft1_shape.jpg", height = 6, width = 8)
    ggsave("size Drinkless n vs ft1_shape.pdf", height = 6, width = 8)
    
# not the graph looks slightly different from the one in overleaf because gt_t_shape in the previous simulation is quadratic_theta
```
